# Generated by Django 5.0.2 on 2024-03-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsimages',
            options={'verbose_name': 'фото', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterField(
            model_name='newsimages',
            name='image',
            field=models.ImageField(upload_to='news/images/%Y/%m/%d/%H-%M-%S/', verbose_name='Фото'),
        ),
    ]
