# Generated by Django 5.0.3 on 2024-03-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional_edu', '0004_alter_docs_options_alter_docsscan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='updated_by',
        ),
    ]
