# Generated by Django 5.0.3 on 2024-03-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_edu', '0006_docs_updated_by_alter_docs_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
    ]
