# Generated by Django 5.0.3 on 2024-03-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_edu', '0007_alter_docs_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='updated_date',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
    ]
