# Generated by Django 5.0.2 on 2024-03-05 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_slider_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='media',
            field=models.ImageField(upload_to='main/slider/%Y-%m-%d-%H-%M-%S/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='owner',
            field=models.ForeignKey(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель поста'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
