# Generated by Django 5.0.2 on 2024-03-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_socialclub'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialClub',
            new_name='SocialMedia',
        ),
    ]
