# Generated by Django 5.0.2 on 2024-03-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_socialclub_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(choices=[('WhatsApp', 'whatsapp'), ('VK', 'vk-com'), ('Telegram', 'telegram'), ('Facebook', 'facebook'), ('Instagram', 'instagram'), ('OK', 'odnoklassniki'), ('TikTok', 'tiktok'), ('Twitter', 'twitter'), ('YouTube', 'youtube')], default=('WhatsApp', 'whatsapp'), max_length=50),
        ),
    ]
