# Generated by Django 5.0.2 on 2024-03-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_socialmedia_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('qr_img', models.ImageField(upload_to='main/qrcodes/%Y-%m-%d-%H-%M-%S/')),
            ],
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('VK', 'VK'), ('Telegram', 'Telegram'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('OK', 'OK'), ('TikTok', 'TikTok'), ('Twitter', 'Twitter'), ('YouTube', 'YouTube')], default=('WhatsApp', 'WhatsApp'), max_length=50),
        ),
    ]
