# Generated by Django 5.0.2 on 2024-03-06 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_qrlink_alter_socialmedia_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrSocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_img', models.ImageField(upload_to='main/qrcodes/%Y-%m-%d-%H-%M-%S/')),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.socialmedia')),
            ],
        ),
        migrations.DeleteModel(
            name='QrLink',
        ),
    ]
