# Generated by Django 5.0.2 on 2024-03-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_qrsocialmedialink_delete_qrlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QrSocialMediaLink',
        ),
    ]
