# Generated by Django 5.0.2 on 2024-03-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_qrsocialmedialink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
