# Generated by Django 5.0.2 on 2024-03-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_slider_usercreated_slider_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='link',
        ),
    ]
