# Generated by Django 5.0.2 on 2024-03-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('bg_img', models.ImageField(upload_to='social_media/titles/%Y/%m/%d-%H-%M-%S/', verbose_name='Изображение')),
                ('qr_code', models.ImageField(upload_to='social_media/qrcodes/%Y/%m/%d-%H-%M-%S/', verbose_name='QR Код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
